version: "3.2"
services:
  redis:
    image: "redis:4-alpine"
    container_name: redis
    command: redis-server --requirepass P@ssw0rd
    volumes:
      - ${PWD}/redis-data:/var/lib/redis
      - ${PWD}/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"