apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kong-pg-pvc
  namespace: kong-ecc
spec:
  storageClassName: kong-pg-data
  accessModes:
    - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 1Gi
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kong-ecc-pvc
  namespace: kong-ecc
spec:
  storageClassName: kong-ecc-data
  accessModes:
    - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 1Gi
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
