services:
    backend:
        image: blockscout/blockscout:7.0.2
        pull_policy: always
        restart: always
        stop_grace_period: 5m
        container_name: backend
        command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        env_file:
            - ../envs/${PREFIX_ENV_PATH:-no-service}-backend.env
        volumes:
            - ./logs/:/app/logs/
            - ./dets/:/app/dets/
            - ../data/genesis.json:/data/genesis.json
