services:
    db-init:
        image: postgres:17
        entrypoint:
            - sh
            - -c
            - |
                chown -R 2000:2000 /var/lib/postgresql/data
        volumes:
            - ./blockscout-db-data:/var/lib/postgresql/data

    db:
        image: postgres:17
        container_name: db
        user: 2000:2000
        shm_size: 256m
        restart: always
        environment:
            POSTGRES_DB: blockscout
            POSTGRES_USER: blockscout
            POSTGRES_PASSWORD: ceWb1MeLBEeOIfk65gU8EjF8
            PGDATA: /var/lib/postgresql/data
        command: postgres -c 'max_connections=200' -c 'client_connection_check_interval=60000'
        volumes:
            - ./blockscout-db-data:/var/lib/postgresql/data
        ports:
            - 7432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U blockscout -d blockscout"] # -d dbname -U user
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
