services:
    frontend:
        image: ghcr.io/blockscout/frontend:v2.1.1
        pull_policy: always
        platform: linux/amd64
        restart: always
        container_name: frontend
        env_file:
            - ../envs/${PREFIX_ENV_PATH:-no-service}-frontend.env
