services:
    proxy:
        image: nginx:latest
        container_name: proxy
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ../proxy/explorer.conf.template:/etc/nginx/templates/default.conf.template
        environment:
            BACK_PROXY_PASS: http://backend:4000
            FRONT_PROXY_PASS: http://frontend:3000
        ports:
            - 80:80
