services:
    stats-db-init:
        image: postgres:17
        entrypoint:
            - sh
            - -c
            - |
                chown -R 2000:2000 /var/lib/postgresql/data
        volumes:
            - ./stats-db-data:/var/lib/postgresql/data

    stats-db:
        image: postgres:17
        container_name: stats-db
        user: 2000:2000
        shm_size: 256m
        restart: always
        environment:
            POSTGRES_DB: stats
            POSTGRES_USER: stats
            POSTGRES_PASSWORD: 9bNzuW6TnFhFhTvnQrfsUyaW
            PGDATA: /var/lib/postgresql/data
        command: postgres -c 'max_connections=200' -c 'client_connection_check_interval=60000'
        volumes:
            - ./stats-db-data:/var/lib/postgresql/data
        ports:
            - 8432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U stats -d stats"] # -d dbname -U user
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

    stats:
        image: ghcr.io/blockscout/stats:v2.9.2
        pull_policy: always
        platform: linux/amd64
        restart: always
        container_name: stats
        extra_hosts:
            - "host.docker.internal:host-gateway"
        env_file:
            - ../envs/service-stats.env
