services:
    postgres:
        image: postgres:15
        container_name: postgres
        shm_size: 256m
        restart: on-failure
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: dbuser
            POSTGRES_PASSWORD: P@ssw0rd
            PGDATA: /var/lib/postgresql/data
            TZ: Asia/Bangkok
        volumes:
            - ${PWD}/postgres-data:/var/lib/postgresql/data
            - ${PWD}/postgres-init:/docker-entrypoint-initdb.d
            - ${PWD}/postgres-config/my-postgres.conf:/etc/postgresql/postgresql.conf
        ports:
            - 5432:5432
