apiVersion: v1
kind: Service
metadata:
  name: test-go-service
  namespace: test
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 31000
  selector:
    app: test-go