apiVersion: apps/v1
kind: Deployment
metadata:
  name: mof-vault-deployment
  namespace: mof-document
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mof-vault-deployment
  template:
    metadata:
      labels:
        app: mof-vault-deployment
    spec:
      containers:
      - name: mof-vault-deployment
        image: kcskbcnd93.kcs:5000/bccommon/vault:1.0.0
        resources:
          requests:
            ephemeral-storage: 1G
          limits:
            ephemeral-storage: 1G
        imagePullPolicy: Always
        args: ["server"]
        readinessProbe:
          exec:
           command:
            - sh
            - -c
        #     - "vault operator unseal 2fd63155cc77d965a046cb8ceb433bba4d5da8becb5f0f76a49bf429a45e1f8c52 && vault operator unseal 808097073b1e8a76e5cac983e8cf502d5194492a9fccff02af40926ef10f256899"
            - "vault operator unseal $VAULT_UNSEAL_KEY1 &&
             vault operator unseal $VAULT_UNSEAL_KEY2 &&
             vault operator unseal $VAULT_UNSEAL_KEY3"
        ports:
          - containerPort: 8200
        securityContext:
          capabilities:
            add: ["IPC_LOCK"]
        env:
          - name: VAULT_ADDR
            value: "http://localhost:8200"
          - name: VAULT_LOCAL_CONFIG
            value: |             
              storage "file" {
                path     = "/vault/data"
              }
             
                listener "tcp" {
                  address = "0.0.0.0:8200"
                  tls_disable = 1
                }
              disable_sealwrap = true
              ui = true
          - name: VAULT_UNSEAL_KEY1
            valueFrom:
              secretKeyRef:
                name: mof-vault-secret
                key: key1
          - name: VAULT_UNSEAL_KEY2
            valueFrom:
              secretKeyRef:
                name: mof-vault-secret
                key: key2        
          - name: VAULT_UNSEAL_KEY3
            valueFrom:
              secretKeyRef:
                name: mof-vault-secret
                key: key3
        volumeMounts:
        - name: mof-vault-data
          mountPath: /vault
      volumes:
      - name: mof-vault-data
        persistentVolumeClaim:
          claimName: mof-vault-pvc
