apiVersion: v1
kind: Service
metadata:
    name: frontend-service
    namespace: arisepreq
    labels:
        app: frontend
spec:
    type: NodePort
    ports:
        - name: http
          port: 3000
          targetPort: 3000
          protocol: TCP
          nodePort: 30080
    selector:
        app: frontend
