apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: arisepreq
  labels:
    app: backend
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: backend
