apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: test
spec:
  type: ClusterIP
  ports:
  - name: default
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres-deployment
