apiVersion: v1
kind: Service
metadata:
  name: dpki-vault-services
  namespace: dpki
spec:
  type: NodePort
  ports:
  - port: 8200
    name: ui
    targetPort: 8200
    nodePort: 30742
  selector:
    app: dpki-vault-deployment
