apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kong-pg-pvc
  namespace: test
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kong-gw-pvc
  namespace: test
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
