# Valid TOML config file
data-path="/opt/besu/data"

# Network
# bootnodes=["enode://001@123:4567", "enode://002@123:4567", "enode://003@123:4567"]

nat-method="DOCKER"
min-gas-price=0

node-private-key-file="/opt/besu/config/key"

p2p-host="172.24.2.4"
p2p-port=30305

rpc-http-enabled=true
rpc-http-host="172.24.2.4"
rpc-http-port=8547
rpc-http-cors-origins=["*"]
rpc-http-api=["ADMIN", "CLIQUE", "DEBUG", "EEA", "ETH", "IBFT", "MINER", "NET", "PERM", "PLUGINS", "PRIV", "QBFT", "TRACE", "TXPOOL", "WEB3"]

revert-reason-enabled=true

# Chain
genesis-file="/opt/besu/config/genesis.json" # Path to the custom genesis file

