apiVersion: v1
kind: Service
metadata:
  name: dscf-vault-services
  namespace: dscf
spec:
  type: NodePort
  ports:
  - port: 8200
    name: ui
    targetPort: 8200
    nodePort: 30700
  selector:
    app: dscf-vault-deployment
