apiVersion: v1
kind: PersistentVolume
metadata:
  name: dscf-vault-pv
  namespace: dscf
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    server: 10.9.211.10
    path: "/NMOF/dscf/vault/"