apiVersion: apps/v1
kind: Deployment
metadata:
  name: guarantor-vault-deployment
  namespace: corp-bc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guarantor-vault-deployment
  template:
    metadata:
      labels:
        app: guarantor-vault-deployment
    spec:
      initContainers:
        - name: init
          image: kcskbcnd93.kcs:5000/utility/busybox:1.28
          command: ['sh', '-c', 'mkdir /vault/config; mkdir /vault/data; chmod 777 -R /vault']
          volumeMounts:
          - name: guarantor-vault-data
            mountPath: /vault
      containers:
      - name: guarantor-vault-deployment
        image: kcskbcnd93.kcs:5000/utility/vault:1.5.5
        resources:
          requests:
            ephemeral-storage: 1G
          limits:
            ephemeral-storage: 1G
        imagePullPolicy: Always
        args: ["server"]
        readinessProbe:
          exec:
           command:
            - sh
            - -c
            - "vault operator unseal $VAULT_UNSEAL_KEY1 &&
             vault operator unseal $VAULT_UNSEAL_KEY2 &&
             vault operator unseal $VAULT_UNSEAL_KEY3"
        ports:
          - containerPort: 8200
        securityContext:
          capabilities:
            add: ["IPC_LOCK"]
        env:
          - name: VAULT_ADDR
            value: "http://localhost:8200"
          - name: VAULT_LOCAL_CONFIG
            value: |             
              storage "file" {
                path     = "/vault/data"
              }
             
                listener "tcp" {
                  address = "0.0.0.0:8200"
                  tls_disable = 1
                }
              disable_sealwrap = true
              ui = true
          - name: VAULT_UNSEAL_KEY1
            valueFrom:
              secretKeyRef:
                name: guarantor-vault-secret
                key: key1
          - name: VAULT_UNSEAL_KEY2
            valueFrom:
              secretKeyRef:
                name: guarantor-vault-secret
                key: key2        
          - name: VAULT_UNSEAL_KEY3
            valueFrom:
              secretKeyRef:
                name: guarantor-vault-secret
                key: key3
        volumeMounts:
        - name: guarantor-vault-data
          mountPath: /vault
      volumes:
      - name: guarantor-vault-data
        persistentVolumeClaim:
          claimName: guarantor-vault-pvc
