apiVersion: v1
kind: Service
metadata:
  name: guarantor-vault-services
  namespace: corp-bc
spec:
  type: NodePort
  ports:
  - port: 8200
    name: ui
    targetPort: 8200
    nodePort: 30800
  selector:
    app: guarantor-vault-deployment
