apiVersion: v1
kind: Service
metadata:
  name: konga-admin
  namespace: test
spec:
  type: NodePort
  ports:
  - name: default
    port: 1337
    targetPort: 1337
    nodePort: 31337
    protocol: TCP
  selector:
    app: konga-deployment

