apiVersion: batch/v1
kind: Job
metadata:
  name: konga-migration
  namespace: test
spec:
  template:
    metadata:
      # creationTimestamp: null
      labels:
        run: konga-migration
    spec:
      containers:
      - name: konga-migration
        image: pantsel/konga:0.14.7
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        command: ["node"]
        args: ["./bin/konga.js", "prepare","--adapter","postgres","--uri","postgresql://postgres:mysecretpassword@postgres-service.test.svc.cluster.local:5432/konga?sslmode=disable"]
        env:
        - name: TOKEN_SECRET
          value: P@ssw0rd
        - name: DB_ADAPTER
          value: postgres
        - name: DB_HOST
          value: "postgres-service.test.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        # - name: DB_USER
        #   value: konga
        # - name: DB_PASSWORD
        #   value: passw0rd
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-db-credential
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-db-credential
              key: password
        - name: DB_DATABASE
          value: konga
        - name: DB_PG_SCHEMA
          value: public
        - name: NODE_ENV
          value: production
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      restartPolicy: Never
status: {}
