version: '2'
services:
  couchdb:
    image: bitnami/couchdb:3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=couchdb
    ports:
      - '5984:5984'  #ui port
      - '4369:4369'
      - '9100:9100'  #cluster port
    volumes:
      - couchdb_data:/bitnami/couchdb
volumes:
  couchdb_data:
    driver: local