services:
    db:
        image: postgres:17
        container_name: db
        shm_size: 256m
        restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-kong}
            POSTGRES_USER: ${POSTGRES_USER:-kong}
            # POSTGRES_PASSWORD: password
            POSTGRES_PASSWORD_FILE: /run/secrets/db_password
            PGDATA: /var/lib/postgresql/data
        command: postgres -c 'max_connections=200' -c 'client_connection_check_interval=60000'
        volumes:
            - ./kong-db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        secrets:
            - db_password
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${POSTGRES_USER:-kong} -d ${POSTGRES_DB:-kong}",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        networks:
            - kong-net

    db-migration:
        image: kong/kong-gateway:${KONG_VERSION:-latest}
        container_name: db-migration
        restart: on-failure
        environment:
            KONG_DATABASE: ${KONG_DATABASE:-postgres}
            KONG_PG_HOST: db
            KONG_PG_DATABASE: ${POSTGRES_DB:-kong}
            KONG_PG_USER: ${POSTGRES_USER:-kong}
            # KONG_PG_PASSWORD: password
            KONG_PG_PASSWORD_FILE: /run/secrets/db_password
            # to secure the admin API or Kong Manager (default username: kong_admin)
            KONG_PASSWORD: ${KONG_PASSWORD:-password}
        command: kong migrations bootstrap
        secrets:
            - db_password
        networks:
            - kong-net
        depends_on:
            db:
                condition: service_healthy

    kong:
        image: kong/kong-gateway:${KONG_VERSION:-latest}
        container_name: kong
        restart: on-failure
        environment:
            KONG_DATABASE: ${KONG_DATABASE:-postgres}
            KONG_PG_HOST: db
            KONG_PG_PORT: 5432
            KONG_PG_DATABASE: ${POSTGRES_DB:-kong}
            KONG_PG_USER: ${POSTGRES_USER:-kong}
            # KONG_PG_PASSWORD: password
            KONG_PG_PASSWORD_FILE: /run/secrets/db_password
            KONG_ADMIN_ACCESS_LOG: /dev/stdout
            KONG_ADMIN_ERROR_LOG: /dev/stderr
            KONG_PROXY_LISTEN: ${KONG_PROXY_LISTEN:-0.0.0.0:8000}
            KONG_ADMIN_LISTEN: ${KONG_ADMIN_LISTEN:-0.0.0.0:8001}
            KONG_ADMIN_GUI_LISTEN: ${KONG_ADMIN_GUI_LISTEN:-0.0.0.0:8002}
            KONG_PROXY_ACCESS_LOG: /dev/stdout
            KONG_PROXY_ERROR_LOG: /dev/stderr
            # KONG_PREFIX: ${KONG_PREFIX:-/var/run/kong}
            # KONG_DECLARATIVE_CONFIG: /opt/kong/kong.yaml
        volumes:
            - ./kong.conf:/etc/kong/kong.conf
        ports:
            - 8000:8000
            - 8001:8001
            - 8002:8002
            - 8443:8443
            - 8444:8444
        secrets:
            - db_password
        healthcheck:
            test: ["CMD", "kong", "health"]
            interval: 10s
            timeout: 10s
            retries: 10
        networks:
            - kong-net
        depends_on:
            db:
                condition: service_healthy
                restart: true

networks:
    kong-net:
        driver: bridge

secrets:
    db_password:
        file: ./DB_PASSWORD
