version: "3.2"
services:
  node1:
    container_name: node1
    image: hyperledger/besu:latest
    environment:
      - LOG4J_CONFIGURATION_FILE=/opt/besu/config/log-config.xml
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu \
        --config-file=/opt/besu/config/config.toml \
        --bootnodes="${BOOTNODE1_ENODE}" \
    volumes:
      - ${PWD}/data:/opt/besu/data
      - ${PWD}/config:/opt/besu/config
      - ${PWD}/logs:/tmp/besu
    ports:
      - 30303:30303
      - 8545:8545
    networks:
      besu:
        ipv4_address: 172.24.2.2

networks:
  besu:
    name: besu
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.2.0/16