apiVersion: v1
kind: PersistentVolume
metadata:
  name: trust-vault-test-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Directory
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /Users/ktb_user/Desktop/kubernetes/vault/local
