apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-1-pvc
  namespace: test 
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  volumeName: volume-1-pv # link with pv name