services:
    mongodb:
        image: mongodb/mongodb-community-server:6.0-ubi8
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-user}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
        volumes:
            - ./mongodb-data:/data/db
        ports:
            - 27017:27017
