services:
    redis-db:
        extends:
            file: ./services/redis.yaml
            service: redis-db

    db-init:
        extends:
            file: ./services/db.yaml
            service: db-init

    db:
        depends_on:
            db-init:
                condition: service_completed_successfully
        extends:
            file: ./services/db.yaml
            service: db

    backend:
        depends_on:
            - db
            - redis-db
        extends:
            file: ./services/backend.yaml
            service: backend
        links:
            - db:database

    frontend:
        depends_on:
            - backend
        extends:
            file: ./services/frontend.yaml
            service: frontend

    proxy:
        depends_on:
            - backend
            - frontend
        extends:
            file: ./services/nginx-explorer.yaml
            service: proxy
